services:
  llm-server:
    image: python:3.10-slim
    container_name: llm-server
    hostname: llm-server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    extra_hosts:
      - "signoz:host-gateway"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=llm-server-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://signoz:4317
    command: sh -c "pip install -r requirements.txt && python llm_server.py"